### ISSUE TITLE
Arachnid Cobweb recipe bug

### ISSUE THREAD

**Issue by ThunderHammer915** [Zentropivity/reorigins#2]
For whatever reason, the Arachnid origin doesn't add a recipe for crafting cobweb out of 2 string like it says it does. I try putting 2 string into 2 slots just like the shown recipe and nothing comes up in the result slot. 
Playing Fabric for 1.19.2, tried both Data Pack and Mod versions. Yes, there are other Origins addons installed, but none of them should be changing the Arachnid origin other than this one

**Comment by Zentropivity** [comment]
Good catch, it seems I left it in that it would cost 6. Fixed now.

**Comment by ThunderHammer915** [comment]
Alright sweet! Thank you!
