### ISSUE TITLE
OriginsTweaks x ReOrigins

### ISSUE THREAD

**Issue by ChromexUnderscore** [Zentropivity/reorigins#3]
Hey, I've stumbled over your port of OriginsTweaks, and I like your changes to it.
So I wanted to ask if its fine with you if I bring those changes to OriginsTweaks?
If you'd like, I can also put a link to your Datapack in my Project desciption stating this as an official port to Quilt and Datapack.
Maybe we can also collaborate on future changes?
Send me an DM on Discord if you're interested! Chromex#9707

**Comment by Zentropivity** [comment]
Hey, feel free to use any parts of this project (and the datapack version), I'm glad you like it.
You could link it but I can not promise that I will update it.
Currently it is pretty rare for me to Minecraft...

**Comment by ChromexUnderscore** [comment]
Alright, thanks!
I'll link your Mod in my project, so that anyone looking for a quilt or datapack version of this mod can find yours!
